# Generated by Django 3.0.5 on 2020-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
