# Generated by Django 3.0.6 on 2020-06-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200525_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Company'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Contractor'),
        ),
    ]
