# Generated by Django 3.0.6 on 2020-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(default='Годовой', max_length=70),
        ),
    ]
