# Generated by Django 3.0.5 on 2020-04-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0018_standardize_description'),
        ('payment', '0003_payment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='circuits',
            field=models.ManyToManyField(blank=True, to='circuits.Circuit'),
        ),
    ]
